apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: rack-1-ippool
spec:
  cidr: 172.16.201.0/24
  blockSize: 24
#  vxlanMode: Always
  vxlanMode: CrossSubnet
#  ipipMode: CrossSubnet
  natOutgoing: true
  nodeSelector: rack == "1"
