apiVersion: v1
kind: Secret
metadata:
  name: harbor
  namespace: devops
data:
 .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJoYXJib3IucXl0YW5naG9zdC5jb20iOiB7CgkJCSJhdXRoIjogIllXUnRhVzQ2UTJsell6QXhNak09IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson