kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nameko-nginx-static-pvc
  namespace: devops
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nameko-nginx-static-storage-class