apiVersion: apps/v1
kind: Deployment
metadata:
  name: affinity-pod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: affinity-pod
  template:
    metadata:
      labels:
        app: affinity-pod
    spec:
      containers:
      - name: affinity-pod
        image: harbor.qytanghost.com/public/nginx_curl
        ports:
        - containerPort: 80
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:  # Pod需要的标签
              matchExpressions:
              - key: qytaffinity
                operator: In
                values:
                - qytang
            topologyKey: rack  # Node需要的标签