apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
  labels:
      addonmanager.kubernetes.io/mode: EnsureExists
data:
  Corefile: |
    .:53 {
        errors
        log
        health
        ready
        prometheus :9153
        kubernetes cluster.local 192.168.0.0/16
        forward . 10.1.1.219
        cache 30
        loop
        reload
        loadbalance
       }
