apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-pod-api-from-yaml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-pod-api-from-yaml
  template:
    metadata:
      labels:
        app: nginx-pod-api-from-yaml
    spec:
      containers:
      - name: nginx-pod-api-from-yaml
        image: harbor.qytanghost.com/public/nginx_curl
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-pod-api-from-yaml
spec:
  selector:
    app: nginx-pod-api-from-yaml
  ports:
    - name: http
      port: 80
      protocol: TCP