apiVersion: v1
kind: Secret
metadata:
 name: harbor-yaml
data:
 .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJoYXJib3IucXl0YW5naG9zdC5jb20iOiB7CgkJCSJhdXRoIjogIllXUnRhVzQ2UTJsell6QXhNak09IgoJCX0KCX0KfQ==
type: kubernetes.io/dockerconfigjson
#[root@master01 ~]# cat .docker/config.json
#{
#        "auths": {
#                "harbor.qytanghost.com": {
#                        "auth": "YWRtaW46Q2lzYzAxMjM="
#                }
#        }

#[root@master01 ~]# cat .docker/config.json | base64
#ewoJImF1dGhzIjogewoJCSJoYXJib3IucXl0YW5naG9zdC5jb20iOiB7CgkJCSJhdXRoIjogIllX
#UnRhVzQ2UTJsell6QXhNak09IgoJCX0KCX0KfQ==