apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-yaml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-yaml
  template:
    metadata:
      labels:
        app: secret-yaml
    spec:
      containers:
      - name: secret-yaml
        image: harbor.qytanghost.com/private/nginx_curl
        volumeMounts:
          - name: secret-volume
            mountPath: /etc/secret-volume
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: harbor-yaml
      volumes:
        - name: secret-volume
          secret:
            secretName: qytang-secret-yaml