apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-kubectl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-kubectl
  template:
    metadata:
      labels:
        app: secret-kubectl
    spec:
      containers:
      - name: secret-kubectl
        image: harbor.qytanghost.com/private/nginx_curl
        volumeMounts:
          - name: secret-volume
            mountPath: /etc/secret-volume
        ports:
        - containerPort: 80
      imagePullSecrets:
        - name: harbor-kubectl
      volumes:
        - name: secret-volume
          secret:
            secretName: qytang-secret-kubectl