apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-curl-probes-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-curl-probes-env
  template:
    metadata:
      labels:
        app: nginx-curl-probes-env
    spec:
      containers:
      - name: nginx-curl-probes-cmd
        image: harbor.qytanghost.com/public/probes:env
        imagePullPolicy: Always
        env:
        - name: startup_delay
          value: "80"
        - name: readiness_time
          value: "160"
        - name: liveliness_time
          value: "240"
        ports:
        - containerPort: 8000
        startupProbe:
          httpGet:
            path: /startup
            port: 8000
          failureThreshold: 30
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          failureThreshold: 1
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /live
            port: 8000
          failureThreshold: 1
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-curl-probes-env
spec:
  clusterIP: 192.168.68.70
  selector:
    app: nginx-curl-probes-env
  ports:
  - name: http
    port: 8000
    protocol: TCP