apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-curl-probes-cmd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-curl-probes-cmd
  template:
    metadata:
      labels:
        app: nginx-curl-probes-cmd
    spec:
      containers:
      - name: nginx-curl-probes-cmd
        image: harbor.qytanghost.com/public/probes:cmd
        imagePullPolicy: Always
        command: ["/qytang/app.py"]
        args: ["-s", "60", "-r", "120", "-l", "180"]
        ports:
        - containerPort: 8000
        startupProbe:
          httpGet:
            path: /startup
            port: 8000
          failureThreshold: 30
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          failureThreshold: 1
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /live
            port: 8000
          failureThreshold: 1
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-curl-probes-cmd
spec:
  clusterIP: 192.168.68.68
  selector:
    app: nginx-curl-probes-cmd
  ports:
  - name: http
    port: 8000
    protocol: TCP