apiVersion: apps/v1
kind: Deployment
metadata:
  name: strategy-recreate
spec:
  replicas: 10
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: strategy-recreate
  template:
    metadata:
      labels:
        app: strategy-recreate
    spec:
      containers:
      - name: strategy-recreate
        image: harbor.qytanghost.com/public/probes:cmd
#        image: harbor.qytanghost.com/public/probes:entrypoint
#        image: harbor.qytanghost.com/public/probes:env
        ports:
        - containerPort: 80