apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-curl-probes-entrypoint
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-curl-probes-entrypoint
  template:
    metadata:
      labels:
        app: nginx-curl-probes-entrypoint
    spec:
      containers:
        - name: nginx-curl-probes-cmd
          image: harbor.qytanghost.com/public/probes:entrypoint
          imagePullPolicy: Always
          args: [ "-s", "10", "-r", "50", "-l", "100" ]
          ports:
            - containerPort: 8000
          startupProbe:
            httpGet:
              path: /startup
              port: 8000
            failureThreshold: 30
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 8000
            failureThreshold: 1
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /live
              port: 8000
            failureThreshold: 1
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-curl-probes-entrypoint
spec:
  clusterIP: 192.168.68.69
  selector:
    app: nginx-curl-probes-entrypoint
  ports:
    - name: http
      port: 8000
      protocol: TCP