apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: traefik
  namespace: kube-system
  labels:
    app: traefik
spec:
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
      annotations:
        prometheus_io_scheme: "traefik"
        prometheus_io_path: "/metrics"
        prometheus_io_port: "8082"
    spec:
      serviceAccountName: traefik-ingress-controller
#      tolerations:
#      - operator: "Exists"
#      nodeSelector:
#        kubernetes.io/hostname: ydzs-master
#      volumes:
#      - name: acme
#        hostPath:
#          path: /data/k8s/traefik/acme
      containers:
      - image: harbor.qytanghost.com/public/traefik:v2.3
        name: traefik
        ports:
        - name: web
          containerPort: 80
          hostPort: 6868
#        - name: websecure
#          containerPort: 443
#          hostPort: 443
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        - name: metrics
          containerPort: 8082
          protocol: TCP
        - name: ping
          containerPort: 8080
          protocol: TCP
        args:
        - --log.level=INFO
        - --accesslog
        - --entryPoints.web.address=:80
#        - --entryPoints.websecure.address=:443
        - --entryPoints.mongo.address=:27017
        - --api=true
        - --api.dashboard=true
        - --ping=true
        - --providers.kubernetesingress
        - --providers.kubernetescrd
        - --serverstransport.insecureskipverify=true
        - --metrics=true
        - --metrics.prometheus=true
        - --metrics.prometheus.buckets=0.100000, 0.300000, 1.200000, 5.000000
        - --metrics.prometheus.entryPoint=metrics
        - --metrics.prometheus.addEntryPointsLabels=true
        - --metrics.prometheus.addServicesLabels=true
        - --entryPoints.metrics.address=:8082
#        - --serversTransport.insecureSkipVerify=true
#        - --experimental.pilot.token=81aaa5f4-54ac-45e5-91a4-d567c3a4bb8e
        # - --providers.file.filename=/config/traefik-tls.toml
        # 使用 dns 验证方式
#        - --certificatesResolvers.ali.acme.dnsChallenge.provider=alidns
        # 邮箱配置
#        - --certificatesResolvers.ali.acme.email=collinsctk@qytang.com
        # 保存 ACME 证书的位置
#        - --certificatesResolvers.ali.acme.storage=/etc/acme/acme.json
        # 下面是用于测试的ca服务，如果https证书生成成功了，则移除下面参数
        # - --certificatesresolvers.ali.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
#        envFrom:
#        - secretRef:
#            name: traefik-alidns-secret
            # ALICLOUD_ACCESS_KEY
            # ALICLOUD_SECRET_KEY
            # ALICLOUD_REGION_ID
#        volumeMounts:
#        - name: acme
#          mountPath: /etc/acme
        # - name: config
        #   mountPath: /config
        # - name: certs
        #   mountPath: /certs
        resources:
          requests:
            cpu: "50m"
            memory: "50Mi"
          limits:
            cpu: "200m"
            memory: "100Mi"
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2

