apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: node-exporter
    app.kubernetes.io/version: v1.2.2
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: node-exporter
  template:
    metadata:
      name: node-exporter
      labels:
        app.kubernetes.io/name: node-exporter
        app.kubernetes.io/version: v1.2.2
    spec:
      volumes:
      - hostPath:
          path: /proc
        name: proc
      - hostPath:
          path: /sys
        name: sys
      - hostPath:
          path: /
        name: root
      containers:
      - name: node-exporter
        image: harbor.qytanghost.com/monitoring/node-exporter:v1.2.2
        resources:
          limits:
            cpu: 500m
            memory: 360Mi
          requests:
            cpu: 500m
            memory: 360Mi
        imagePullPolicy: IfNotPresent
        args:
        - --path.procfs=/host/proc
        - --path.sysfs=/host/sys
        - --path.rootfs=/host/root
#        - --no-collector.wifi
#        - --no-collector.hwmon
#        - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+|var/lib/kubelet/pods/.+)($|/)\
#        - --collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)
        ports:
        - name: node-exporter
#          hostPort: 9100
          containerPort: 9100
          protocol: TCP
        volumeMounts:
          - mountPath: /host/proc
            mountPropagation: HostToContainer
            name: proc
            readOnly: true
          - mountPath: /host/sys
            mountPropagation: HostToContainer
            name: sys
            readOnly: true
          - mountPath: /host/root
            mountPropagation: HostToContainer
            name: root
            readOnly: true
#      hostNetwork: true
      tolerations:
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule