apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-curl-emptydir # deployment的名字
spec:
  replicas: 1 # deployment必须指定副本数量
  selector:
    matchLabels:
      app: nginx-curl-emptydir # 选择器匹配的标签
  template:
    metadata:
      labels:
        app: nginx-curl-emptydir # 标签
    spec:
      containers:
      - name: nginx-curl-emptydir # 容器的名字, 一个pod内可以有多个容器
        image: harbor.qytanghost.com/public/nginx_curl # 容器的镜像
        volumeMounts:
          - name: emptydir
            mountPath: /emptydir
        ports:
        - containerPort: 80 # 只是一个信息, 类似于Dockerfile的EXPOSE
      volumes:
        - name: emptydir
          emptyDir:
#            medium: "Memory"
            sizeLimit: "300Mi"